version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: limoha/devops-for-programmers-project-lvl1
    volumes:
      - app:/app:cached
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_NAME: postgres 
      POSTGRES_HOST_AUTH_METHOD: trust
    command: npm test

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_NAME: postgres 
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  app:
  pgdata:
