version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: limoha/devops-for-programmers-project-lvl1
    volumes:
      - app:/app:cached
    depends_on:
      - db
    env_file:
      - app/.env
    command: npm test

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_NAME: postgres 
volumes:
  app:
