version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app:cached
    command: npm start
    ports:
      - "0.0.0.0:8080:8080"
  caddy:
    image: caddy:latest
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    
volumes:
  app:
  caddy_data:
  caddy_config:
