version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: limoha/devops-for-programmers-project-lvl1
    volumes:
      - app:/app:cached
    depends_on:
      - db
    command: npm test
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    
volumes:
  app:
