version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: limoha/devops-for-programmers-project-lvl1
    volumes:
      - app:/app:cached
    command: npm test
volumes:
  app:
