version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: limoha/devops-for-programmers-project-lvl1
    depends_on:
      - db
    environment:
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_NAME: postgres 
      DATABASE_USERNAME: postgres
    command: npm test

  db:
    image: postgres:12-alpine
    environment:
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_NAME: postgres 
      DATABASE_USERNAME: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  app:
  pgdata:
